apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: peakblockanalytics 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: peakblockanalytics 
    spec:
      containers:
        - name: peakblockanalytics 
          image: cohub.azurecr.io/peakblockanalytics
          ports:
          - containerPort: 5555